version: '3.8'

services:
  base-serivce:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: osage-base
    container_name: base_container
    command: tail -F anything



  tigress:
    build:
      context: .
      dockerfile: Dockerfile.tigress
    image: osage-tigress
    container_name: tigress_container
    depends_on:
      - base-serivce
    command: tail -F anything


#  gcc:
#    build:
#      context: .
#      dockerfile: Dockerfile.gcc
#    image: osage-gcc
#    container_name: gcc_container
#    depends_on:
#      - base
#    command: tail -F anything

#  llvm:
#    build:
#      context: .
#      dockerfile: Dockerfile.llvm
#    container_name: llvm_container
#    depends_on:
#      - base
#    command: tail -F anything

#  musl:
#    build:
#      context: .
#      dockerfile: Dockerfile.musl
#    container_name: musl_container
#    depends_on:
#      - base
#    command: tail -F anything

#  ollvm:
#    build:
#      context: .
#      dockerfile: Dockerfile.ollvm
#    container_name: ollvm_container
#    depends_on:
#      - base
#    command: tail -F anything



#  tinycc:
#    build:
#      context: .
#      dockerfile: Dockerfile.tinycc
#    container_name: tinycc_container
#    depends_on:
#      - base
#    command: tail -F anything
#
#  tendra:
#    build:
#      context: .
#      dockerfile: Dockerfile.tendra
#    container_name: tendra_container
#    depends_on:
#      - base
#    command: tail -F anything