FROM base:latest

# Install coreutils to ensure tail is available
RUN pacman -S --noconfirm coreutils

# Install Tigress
COPY build_tigress.sh /opt/build_scripts/
COPY tigress-versions/tigress-3.3.3-bin.zip /opt/samplegenerator/tigress-versions/
RUN bash /opt/build_scripts/build_tigress.sh