FROM archlinux:base-devel
MAINTAINER nobody@fhstp.ac.at

# Update and install base packages
RUN set -eux; \
    echo -e "[multilib] \n Include = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf; \
    pacman -Syyu --noconfirm; \
    pacman -S --noconfirm \
        base-devel git gcc gcc-multilib clang llvm musl cmake bmake lib32-glibc \
        pcre zlib libevent ncurses lua53 libdeflate curl unzip zip upx shellcheck \
        python3 flake8 python-flake8-docstrings mypy python-pytest python-pytest-cov \
        python-magic python-pip python-pandas python-psutil python-capstone \
        python-pyelftools python-termcolor python-rzpipe opam coreutils

# Clear package cache
RUN pacman -Scc --noconfirm

# Verify the tail command
RUN which tail && ls -l $(which tail)

# Link /usr/lib/i386-linux-gnu/ to /usr/lib32
RUN cd /usr/lib/ && \
    ln -s /usr/lib32 i386-linux-gnu

# Copy the code directory to /opt
COPY ./ /opt/samplegenerator

# Remove the code if the version is not given. If there is no version it is no release!
RUN if [ -z "$version" ] ; then \
        rm -rf /opt/samplegenerator; \
    else \
        # Make all shell scripts executable
        find /opt/samplegenerator/ -name "*.sh" | xargs -I {} chmod a+x {}; \
    fi

WORKDIR /opt/samplegenerator/