FROM base:latest

# Install coreutils to ensure tail is available
RUN pacman -S --noconfirm coreutils

# Install Tendra
COPY build_tendra.sh /opt/build_scripts/
RUN bash /opt/build_scripts/build_tendra.sh