@startuml
skinparam backgroundColor #FEFEFE
folder src as src_dir {
    folder src_coreutils as sr_src_coreutils {
        folder ls as src_src_coreutils_ls {
            label "..." as src_coreutils_ls_label
        }
    }
    folder src_strings {
        folder anagram as src_src_strings_anagram {
            file anagram.c as anagram_c {
                label "main()..."
            }
            file anagram.metadata.assets.functions.txt {
                label "main\ncheckAnagram"
            }
            file anagram.metadata.backdoor.toml {
                label "[backdoor]\n    arguments = ['83R35whTPF83R35whTPF' '83R35whTPF83R35whTPF']\n    stdout = 'Backdoor triggered!\\n'"
            }
            file anagram.metadata.options.txt {
                label "-I. -Ilib -Isrc -c"
            }
        }
        folder src_strings_reversestring as "reversestring"{
            label "..." as src_strings_reversestring_label
        }
    }
}
folder compiler as compiler_dir {
    folder compiler_compiler {
        folder gcc_15_1_0 {
            folder build as gcc_15_1_0_build {
                file gcc_15_1_0.Dockerfile {
                    label "FROM gcc:15.1.0"
                }
                file mapper.sh as gcc_15_1_0.mapper.sh {
                    label "sample="$1"\n recipe="$2" "
                }
            }
            file config.yml as gcc_15_1_0.config.yml {
            }
            folder recipes as gcc_15_1_0_recipes {
                folder recipes_o_level as gcc_15_1_0_recipes_recipes_o_level {
                    folder o_level_0 as gcc_15_1_0_recipes_recipes_o_level_o_level_0 {
                        file o_level_o.arg {
                            label "-Wall -Wextra -O0"
                        }
                    }
                }
            }
        }
    }
}
folder analyzer as analyzer_dir {
    folder analyzer_statistics as analyzer_analyzer_statistics {
        folder out_statistics as analyzer_analyzer_statistics_out_statistics {
            folder build as analyzer_analyzer_statistics_out_statistics_build {
                file out_statistics.Dockerfile {
                    label "FROM python:3.13.5"
                }
            }
            folder recipes as analyzer_analyzer_statistics_out_statistics_recipes {
                folder out_statistics as analyzer_analyzer_statistics_out_statistics_recipes_out_statistics {
                    folder out_statistics as analyzer_analyzer_statistics_out_statistics_recipes_out_statistics_out_statistics {
                        file out_statistics.py {
                            label "#!/bin/python"
                        }
                    }
                }
            }
        }
    }
}
folder out as out_dir {
    folder run_2025_07_09_10_20_00 as run {
        folder src_strings as src_strings_out {
            folder anagram as anagram_dir_out {
                folder "gcc_15_1_0-o_level_0" as out_run_src_strings_anagram_gcc_O0 {
                    file anagram.out as anagram_out {
                        label "101101010110"
                    }
                    file anagram.log as anagram_log {
                        label "log..."
                    }
                    folder out_statistics as out_run_src_strings_anagram_gcc_O0_out_statistics {
                        file anagram.out_statistics.csv {
                            label "executable_exists,executable_permissions_x,...\n True,True,..."
                        }
                    }
                }
            }
        }
    }
}
node Osagecontainer001 as container001 {
    label "compilation container"
}
node Osagecontainer002 as container002 {
    label "analysis container"
}
' Compilation
anagram_c -[#blue]-> container001
gcc_15_1_0_recipes_recipes_o_level_o_level_0 -[#blue]-> container001
container001 -[#blue]-> anagram_out
container001 -[#blue]-> anagram_log

' analysis
src_src_strings_anagram -[#red]-> container002
out_run_src_strings_anagram_gcc_O0 -[#red]-> container002
container002 -[#red]-> out_run_src_strings_anagram_gcc_O0_out_statistics
analyzer_analyzer_statistics_out_statistics_recipes_out_statistics_out_statistics -[#red]-> container002

' FORCE Positioning of the folders
' src_dir -[hidden]d- compiler_dir
' compiler_dir -[hidden]d- out_dir
@enduml
