/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

struct _4_init_program_1_opaque_NodeStruct ;
struct _IO_FILE ;
struct timeval ;
extern int gettimeofday(struct timeval *tv , void *tz ) ;
extern int pthread_cond_broadcast(int *cond ) ;
char **_global_argv  =    (char **)0;
extern int getpagesize() ;
extern int posix_memalign(void **memptr , unsigned int alignment , unsigned int size ) ;
struct _4_init_program_1_opaque_NodeStruct {
   int data ;
   struct _4_init_program_1_opaque_NodeStruct *next ;
   struct _4_init_program_1_opaque_NodeStruct *prev ;
};
extern int pthread_join(void *thread , void **value_ptr ) ;
unsigned int BPHash(char *str , unsigned int len ) ;
extern int open(char const   *filename , int oflag  , ...) ;
typedef unsigned long size_t;
extern  __attribute__((__nothrow__)) size_t ( __attribute__((__nonnull__(1), __leaf__)) strlen)(char const   *__s )  __attribute__((__pure__)) ;
extern int pthread_barrier_destroy(int *barrier ) ;
extern int pthread_mutex_init(int *mutex , int *attr ) ;
extern int strncmp(char const   *s1 , char const   *s2 , unsigned int maxlen ) ;
extern int printf(char const   * __restrict  __format  , ...) ;
int _global_argc  =    0;
extern int pthread_cond_signal(int *cond ) ;
extern int pthread_barrier_init(int *barrier , int *attr , unsigned int count ) ;
extern int scanf(char const   *format  , ...) ;
extern int raise(int sig ) ;
char **_global_envp  =    (char **)0;
extern int unlink(char const   *filename ) ;
unsigned long _3_alwaysZero  =    0;
extern int pthread_barrier_wait(int *barrier ) ;
extern double difftime(long tv1 , long tv0 ) ;
extern void *memcpy(void *s1 , void const   *s2 , unsigned int size ) ;
extern int pthread_mutex_lock(int *mutex ) ;
extern int gethostname(char *name , unsigned int namelen ) ;
extern void *dlsym(void *handle , char *symbol ) ;
extern unsigned long strtoul(char const   *str , char const   *endptr , int base ) ;
extern void abort() ;
extern int fprintf(struct _IO_FILE *stream , char const   *format  , ...) ;
extern void free(void *ptr ) ;
int main(int argc , char **argv , char **_formal_envp ) ;
extern void signal(int sig , void *func ) ;
extern void exit(int status ) ;
unsigned long _3_entropy  =    5543421374015659211UL;
typedef struct _IO_FILE FILE;
extern int close(int filedes ) ;
extern int mprotect(void *addr , unsigned int len , int prot ) ;
extern double log(double x ) ;
extern double strtod(char const   *str , char const   *endptr ) ;
struct _4_init_program_1_opaque_NodeStruct *_4_init_program_1_opaque_list_1  =    (struct _4_init_program_1_opaque_NodeStruct *)0;
extern double ceil(double x ) ;
extern int fclose(void *stream ) ;
extern int fcntl(int filedes , int cmd  , ...) ;
extern int pthread_cond_wait(int *cond , int *mutex ) ;
extern void perror(char const   *str ) ;
extern int write(int filedes , void *buf , unsigned int nbyte ) ;
extern int pthread_cond_init(int *cond , int *attr ) ;
void init_program(void) ;
extern int ptrace(int request , void *pid , void *addr , int data ) ;
extern float strtof(char const   *str , char const   *endptr ) ;
extern unsigned int strnlen(char const   *s , unsigned int maxlen ) ;
struct timeval {
   long tv_sec ;
   long tv_usec ;
};
extern long clock(void) ;
extern void qsort(void *base , unsigned int nel , unsigned int width , int (*compar)(void *a ,
                                                                                     void *b ) ) ;
extern long time(long *tloc ) ;
extern int read(int filedes , void *buf , unsigned int nbyte ) ;
extern int rand() ;
struct _4_init_program_1_opaque_NodeStruct *_4_init_program_1_opaque_list_2  =    (struct _4_init_program_1_opaque_NodeStruct *)0;
extern int strcmp(char const   *a , char const   *b ) ;
extern void *fopen(char const   *filename , char const   *mode ) ;
extern double sqrt(double x ) ;
extern void *malloc(unsigned int size ) ;
extern int snprintf(char *str , unsigned int size , char const   *format  , ...) ;
extern long strtol(char const   *str , char const   *endptr , int base ) ;
struct _4_init_program_1_opaque_NodeStruct *_4_init_program_1_opaque_ptr_1  =    (struct _4_init_program_1_opaque_NodeStruct *)0;
extern int nanosleep(int *rqtp , int *rmtp ) ;
extern int pthread_mutex_unlock(int *mutex ) ;
typedef struct _4_init_program_1_opaque_NodeStruct *_4_init_program_1_opaque_StructureType;
extern int pthread_create(void *thread , void *attr , void *start_routine , void *arg ) ;
extern int atoi(char const   *s ) ;
void _5_bf_1(unsigned long offset )  __attribute__((__optimize__(0), __optimize__("-fno-omit-frame-pointer"),
__noinline__)) ;
unsigned int _4_init_program__opaque_array[30]  = 
  {      448,      110,      3,      318, 
        523,      5,      33,      208, 
        5,      183,      313,      7, 
        83,      474,      11,      48, 
        446,      42,      68,      292, 
        25,      143,      40,      22, 
        403,      544,      79,      43, 
        89};
extern int fscanf(struct _IO_FILE *stream , char const   *format  , ...) ;
extern int fseek(struct _IO_FILE *stream , long offs , int whence ) ;
struct _4_init_program_1_opaque_NodeStruct *_4_init_program_1_opaque_ptr_2  =    (struct _4_init_program_1_opaque_NodeStruct *)0;
void megaInit(void) ;
int main(int argc , char **argv , char **_formal_envp ) 
{ 
  char *str ;
  unsigned int hash ;
  size_t tmp ;
  int _BARRIER_0 ;

  {
  megaInit();
  _global_argc = argc;
  _global_argv = argv;
  _global_envp = _formal_envp;
  _BARRIER_0 = 1;
  str = *(argv + 1);
  init_program();
  tmp = strlen((char const   *)str);
  hash = BPHash(str, (unsigned int )tmp);
  if (hash == 244939252U) {
    printf((char const   */* __restrict  */)"You win!\n");
  } else {
    printf((char const   */* __restrict  */)"You loose!\n");
  }
  printf((char const   */* __restrict  */)"Hash: 0x%x\n", hash);
  return (0);
}
}
void _5_bf_1(unsigned long offset )  __attribute__((__optimize__(0), __optimize__("-fno-omit-frame-pointer"),
__noinline__)) ;
void _5_bf_1(unsigned long offset ) 
{ 


  {
  __asm__  volatile   ("movq  %0, 8(%%rbp)": : "r" (offset));
}
}
void megaInit(void) 
{ 


  {

}
}
unsigned int BPHash(char *str , unsigned int len ) 
{ 
  unsigned int hash ;
  unsigned int i ;

  {
  hash = 0U;
  i = 0U;
  i = 0U;
  while (i < len) {
    hash = (hash << 7) ^ (unsigned int )*str;
    str ++;
    i ++;
  }
  return (hash);
}
}
void init_program(void) 
{ 
  struct _4_init_program_1_opaque_NodeStruct *p1 ;
  int i2 ;
  struct _4_init_program_1_opaque_NodeStruct *p3 ;
  int _4_init_program__BEGIN_1 ;
  int _4_init_program__END_1 ;
  int _4_init_program__BARRIER_2 ;

  {
  {  /* __blockattribute__(__ATOMIC__)*/ 
  _4_init_program__BEGIN_1 = 1;
  p1 = (struct _4_init_program_1_opaque_NodeStruct *)malloc(sizeof(struct _4_init_program_1_opaque_NodeStruct ));
  p1->next = p1;
  p1->prev = p1;
  _4_init_program_1_opaque_list_1 = p1;
  i2 = 0;
  while (i2 < 2) {
    p3 = (struct _4_init_program_1_opaque_NodeStruct *)malloc(sizeof(struct _4_init_program_1_opaque_NodeStruct ));
    p3->data = i2 * ((_3_entropy & 4) * (_3_entropy | 4) + (_3_entropy & ~ 4) * (~ _3_entropy & 4));
    p3->next = _4_init_program_1_opaque_list_1->next;
    p3->prev = _4_init_program_1_opaque_list_1;
    (_4_init_program_1_opaque_list_1->next)->prev = p3;
    _4_init_program_1_opaque_list_1->next = p3;
    i2 ++;
  }
  _4_init_program_1_opaque_ptr_1 = _4_init_program_1_opaque_list_1->next;
  _4_init_program_1_opaque_ptr_2 = _4_init_program_1_opaque_ptr_1;
  _4_init_program_1_opaque_ptr_2 = _4_init_program_1_opaque_ptr_2->next;
  _4_init_program__END_1 = 1;
  }
  _4_init_program__BARRIER_2 = 1;

  {
  if (_4_init_program_1_opaque_ptr_1 != _4_init_program_1_opaque_ptr_2) {
    return;
  } else {

  }
  }
}
}
