[testcase_001]
    arguments = ["0",]
    stdout = "Result: 0\n"
    exit_code = 0

[testcase_002]
    arguments = ["1",]
    stdout = "Result: 1\n"
    exit_code = 0

[testcase_003]
    arguments = ["10",]
    stdout = "Result: 2\n"
    exit_code = 0

[testcase_004]
    arguments = ["11",]
    stdout = "Result: 3\n"
    exit_code = 0

[testcase_005]
    arguments = ["101",]
    stdout = "Result: 5\n"
    exit_code = 0

[testcase_006]
    arguments = ["110",]
    stdout = "Result: 6\n"
    exit_code = 0

[testcase_007]
    arguments = ["1010",]
    stdout = "Result: 10\n"
    exit_code = 0

[testcase_008]
    arguments = ["1111",]
    stdout = "Result: 15\n"
    exit_code = 0

[testcase_missing_args]
    arguments = []
    stdout = ""
    exit_code = 2
