[testcase_001]
    arguments = ["a",]
    stdout = "Result: 0xe8b7be43\n"
    exit_code = 0

[testcase_002]
    arguments = ["hello",]
    stdout = "Result: 0x3610a686\n"
    exit_code = 0

[testcase_003]
    arguments = ["world",]
    stdout = "Result: 0x3a771143\n"
    exit_code = 0

[testcase_004]
    arguments = ["foo",]
    stdout = "Result: 0x8c736521\n"
    exit_code = 0

[testcase_005]
    arguments = ["bar",]
    stdout = "Result: 0x76ff8caa\n"
    exit_code = 0

[testcase_006]
    arguments = ["12345",]
    stdout = "Result: 0xcbf53a1c\n"
    exit_code = 0

[testcase_007]
    arguments = ["Hello, World!",]
    stdout = "Result: 0xec4ac3d0\n"
    exit_code = 0

[testcase_008]
    arguments = ["coreutils",]
    stdout = "Result: 0x3bcfe8c5\n"
    exit_code = 0

[testcase_invalid_no_args]
    arguments = []
    stdout = ""
    exit_code = 2
