[testcase_001]
    arguments = ["a",]
    stdout = "Result: 0x41\n"
    exit_code = 0

[testcase_002]
    arguments = ["hello",]
    stdout = "Result: 0xcb33def\n"
    exit_code = 0

[testcase_003]
    arguments = ["world",]
    stdout = "Result: 0xd4645e4\n"
    exit_code = 0

[testcase_004]
    arguments = ["foo",]
    stdout = "Result: 0x158f\n"
    exit_code = 0

[testcase_005]
    arguments = ["bar",]
    stdout = "Result: 0x452\n"
    exit_code = 0

[testcase_006]
    arguments = ["12345",]
    stdout = "Result: 0x909cab5\n"
    exit_code = 0

[testcase_007]
    arguments = ["Hello, World!",]
    stdout = "Result: 0x1bf552d7\n"
    exit_code = 0

[testcase_008]
    arguments = ["coreutils",]
    stdout = "Result: 0x4d6ae997\n"
    exit_code = 0

[testcase_invalid_no_args]
    arguments = []
    stdout = ""
    exit_code = 2
