[testcase_valid]
    arguments = ["123",]
    stdout = "Result: 123_10 = 7B_16\n"
    exit_code = 0

[testcase_invalid]
    arguments = ["abc",]
    stdout = "Result: abc_10 is not a valid number.\n"
    exit_code = 1
