##testcase and size are mandatory
#[add]
#testcase=int
#size=2
#
#[fib]
#testcase=int
#size=1
#
#[dummy]
#testcase=fileinput
#size=1000
#type=string
#args=<in>
#outfilename=dummy.outfile
#
#[dummy2]
#testcase=fileinput
#size=1000
#type=string
#args=<in>
#outfilename=dummy.outfile

##SORT START
##[sort]
##testcase=int
##size=1000
#
##[sort100]
##testcase=int
##size=1000
#
##[mul]
##testcase=int
##size=2
#
##TODO main readin 2 go:
#[readin]
#testcase=fileinput
#size=1000
#type=string
#args=<in> <out>
#outfilename=readin.outfile
#

########################################
# HASH WITH ARGUMENTS ##################
########################################

[bkdrhash]
testcase=string
size=1000

[bphash]
testcase=string
size=1000

[dekhash]
testcase=string
size=1000

[djbhash]
testcase=string
size=1000

[onelua]
testcase=string
size=1000

[echo]
testcase=string
size=1000

[wc]
testcase=string
size=1000

[shell]
testcase=string
size=1000

[elfhash]
testcase=string
size=1000

[fnvhash]
testcase=string
size=1000

[jshash]
testcase=string
size=1000

[nohash]
testcase=string
size=1000

[pjwhash]
testcase=string
size=1000

[rshash]
testcase=string
size=1000

[sdbmhash]
testcase=string
size=1000

[md5hash]
testcase=string
size=1000

[xorffhash]
testcase=string
size=1000

[adler32hash]
testcase=string
size=1000

[crc32hash]
testcase=string
size=1000

########################################
# HASH WITH FILE #######################
########################################

[bkdrhash_file]
testcase=fileinput
size=1000
type=string
args=<in>
outfilename=bkdrhash.outfile

[bphash_file]
testcase=fileinput
size=1000
type=string
args=<in>
outfilename=bphash.outfile

[dekhash_file]
testcase=fileinput
size=1000
type=string
args=<in>
outfilename=dekhash.outfile

[djbhash_file]
testcase=fileinput
size=1000
type=string
args=<in>
outfilename=djbhash.outfile

[elfhash_file]
testcase=fileinput
size=1000
type=string
args=<in>
outfilename=elfhash.outfile

[fnvhash_file]
testcase=fileinput
size=1000
type=string
args=<in>
outfilename=fnvhash.outfile

[jshash_file]
testcase=fileinput
size=1000
type=string
args=<in>
outfilename=jshash.outfile

[nohash_file]
testcase=fileinput
size=1000
type=string
args=<in>
outfilename=nohash.outfile

[pjwhash_file]
testcase=fileinput
size=1000
type=string
args=<in>
outfilename=pjwhash.outfile

[rshash_file]
testcase=fileinput
size=1000
type=string
args=<in>
outfilename=rshash.outfile

[sdbmhash_file]
testcase=fileinput
size=1000
type=string
args=<in>
outfilename=sdbmhash.outfile

########################################
# SORT WITH ARGUMENTS ##################
########################################

[bubblesort]
testcase=int
size=1000

[insertionsort]
testcase=int
size=1000

[mergesort]
testcase=int
size=1000

[quicksort]
testcase=int
size=1000

[selectionsort]
testcase=int
size=1000

########################################
# SORT WITH file #######################
########################################

[bubblesort_file]
testcase=fileinput
size=1000
type=int
args=<in>
outfilename=bubblesort_file.outfile

[insertionsort_file]
testcase=fileinput
size=1000
type=int
args=<in>
outfilename=insertionsort_file.outfile

[mergesort_file]
testcase=fileinput
size=1000
type=int
args=<in>
outfilename=mergesort_file.outfile

[quicksort_file]
testcase=fileinput
size=1000
type=int
args=<in>
outfilename=quicksort_file.outfile

[selectionsort_file]
testcase=fileinput
size=1000
type=int
args=<in>
outfilename=selectionsort_file.outfile

########################################
# Testcases for coreutils ##############
########################################

[\[_8_32]
testcase=arguments
args=--version

[b2sum_8_32]
testcase=fileinput
size=1000
type=string
args=<in>

[base32_8_32]
testcase=fileinput
size=1000
type=string
args=<in>

[base64_8_32]
testcase=fileinput
size=1000
type=string
args=<in>

[basename_8_32]
testcase=filepath
size=2
type=random
args=-a <in>

[basenc_8_32]
testcase=fileinput
size=1000
type=string
args=--base2lsbf <in>

[bzip2_1_0_6]
testcase=fileinput
size=1000
type=string
args=-k -z <in>

[cat_8_32]
testcase=fileinput
size=1000
type=string
args=<in>

[chcon_8_32]
testcase=arguments
args=--version

[chgrp_8_32]
testcase=arguments
args=--version

[chmod_8_32]
testcase=arguments
args=--version

[chown_8_32]
testcase=arguments
args=--version

[chroot_8_32]
testcase=arguments
args=--version

[cksum_8_32]
testcase=fileinput
size=1000
type=string
args=<in>

[comm_8_32]
testcase=fileinput
size=1000
type=string
args=<in> <in>

[cp_8_32]
testcase=fileinput
size=1000
type=string
args=<in> <out>

[csplit_8_32]
testcase=fileinput
size=1000
type=string
args=<in> '/ /'

[cut_8_32]
testcase=fileinput
count=50
size=100
type=string
seperator=newline
args=--characters=2-4 <in>

[date_8_32]
testcase=arguments
args=--rfc-3339='ns'

[dd_8_32]
testcase=arguments
args=--version

[df_8_32]
testcase=arguments
args=-a -h

[dir_8_32]
testcase=filepath
type=existing
args=-a <in>

[dircolors_8_32]
testcase=arguments
args=-p

[dirname_8_32]
testcase=filepath
size=2
type=random
args=-a <in>

[du_8_32]
testcase=filepath
type=existing
args=-hs <in>

[echo_8_32]
testcase=string
size=100

[env_8_32]
testcase=arguments
args=--version

[expand_8_32]
testcase=fileinput
count=50
size=100
type=string
seperator=tab
args=<in>

[expr_8_32]
testcase=arguments
args=length "test" ">" 5 "&" 22 - 5 ">" 15

[factor_8_32]
testcase=int
size=100

[false_8_32]
testcase=arguments
args=--version

[fmt_8_32]
testcase=fileinput
size=1000
type=string
args=<in>

[fold_8_32]
testcase=fileinput
count=50
size=100
type=string
seperator=newline
args=<in>

[getlimits_8_32]
testcase=arguments
args=--version

[ginstall_8_32]
testcase=arguments
args=--version

[groups_8_32]
testcase=arguments
args=

[head_8_32]
testcase=fileinput
count=50
size=100
type=string
seperator=newline
args=<in>

[hostid_8_32]
testcase=arguments
args=--version

[join_8_32]
testcase=arguments
args=--version

[kill_8_32]
testcase=arguments
args=--version

[link_8_32]
testcase=arguments
args=--version

[ln_8_32]
testcase=arguments
args=--version

[logname_8_32]
testcase=arguments
args=

[ls_8_32]
testcase=filepath
type=existing
args=-a <in>

[md5sum_8_32]
testcase=fileinput
size=1000
type=string
args=<in>

[mkdir_8_32]
testcase=arguments
args=--version

[mkfifo_8_32]
testcase=arguments
args=--version

[mknod_8_32]
testcase=arguments
args=--version

[mktemp_8_32]
testcase=arguments
args=--version

[mv_8_32]
testcase=arguments
args=--version

[nice_8_32]
testcase=arguments
args=--version

[nl_8_32]
testcase=fileinput
size=1000
type=string
args=<in>

[nohup_8_32]
testcase=arguments
args=--version

[nproc_8_32]
testcase=arguments
args=--all

[numfmt_8_32]
testcase=int
size=1000
args=--to=si <in>

[paste_8_32]
testcase=fileinput
count=50
size=100
type=string
seperator=newline
args=<in> <in>

[pathchk_8_32]
testcase=filepath
type=existing
args=-p <in>

[pinky_8_32]
testcase=arguments
args=

[printenv_8_32]
testcase=arguments
args=

[printf_8_32]
testcase=arguments
args=\"Test\\\t\vTEST

[ptx_8_32]
testcase=fileinput
count=50
size=100
type=string
seperator=newline
args=<in>

[pwd_8_32]
testcase=arguments
args=--logical

[readlink_8_32]
testcase=arguments
args=--version

[realpath_8_32]
testcase=filepath
type=existing
args=--relative-to=/var <in>

[rm_8_32]
testcase=arguments
args=--version

[rmdir_8_32]
testcase=arguments
args=--version

[runcon_8_32]
testcase=arguments
args=--version

[seq_8_32]
testcase=int
size=1

[sha1sum_8_32]
testcase=fileinput
size=1000
type=string
args=<in>

[sha224sum_8_32]
testcase=fileinput
size=1000
type=string
args=<in>

[sha256sum_8_32]
testcase=fileinput
size=1000
type=string
args=<in>

[sha384sum_8_32]
testcase=fileinput
size=1000
type=string
args=<in>

[sha512sum_8_32]
testcase=fileinput
size=1000
type=string
args=<in>

[shred_8_32]
testcase=arguments
args=--version

[shuf_8_32]
testcase=fileinput
size=1000
type=string
args=<in>

[sleep_8_32]
testcase=int
min=1
max=5
size=1

[sort_8_32]
testcase=fileinput
size=1000
type=string
args=<in>

[stat_8_32]
testcase=filepath
type=existing
args=<in>

[stdbuf_8_32]
testcase=arguments
args=--version

[stty_8_32]
testcase=arguments
args=-a

[sync_8_32]
testcase=arguments
args=

[tac_8_32]
testcase=fileinput
size=1000
type=string
args=<in>

[tail_8_32]
testcase=fileinput
count=50
size=100
type=string
seperator=newline
args=<in>

[tee_8_32]
testcase=arguments
args=--version

[test_8_32]
testcase=arguments
args=--version

[timeout_8_32]
testcase=arguments
args=--version

[touch_8_32]
testcase=arguments
args=--version

[tr_8_32]
testcase=arguments
args=--version

[true_8_32]
testcase=arguments
args=--version

[truncate_8_32]
testcase=arguments
args=--version

[tsort_8_32]
testcase=arguments
args=--version

[uname_8_32]
testcase=arguments
args=-a

[unexpand_8_32]
testcase=fileinput
count=50
size=100
type=string
seperator=space
args=--tabs=1 <in>

[uniq_8_32]
testcase=fileinput
count=50
size=100
type=string
seperator=newline
args=--count <in>

[unlink_8_32]
testcase=arguments
args=--version

[uptime_8_32]
testcase=arguments
args=-p

[users_8_32]
testcase=arguments
args=

[vdir_8_32]
testcase=filepath
type=existing
args=-a <in>

[wc_8_32]
testcase=fileinput
count=50
size=100
type=string
seperator=newline
args=<in>

[who_8_32]
testcase=arguments
args=-a

[whoami_8_32]
testcase=arguments
args=

[yes_8_32]
testcase=arguments
args=--version

[lighttpd_1_4_59]
testcase=arguments
args=--version

[nginx_1_21_3]
testcase=arguments
args=--version

[tmux_3_2_a]
testcase=arguments
args=--version


########################################
# Testcases for DGAS ###################
########################################

[dgaramdo]
testcase=run

########################################
# Testcases for math ###################
########################################

[areacircle]
testcase=int
size=1

########################################
# Testcases for converter ##############
########################################

[binary2decimal]
testcase=bin
size=1

[binary2octal]
testcase=bin
size=1

[celcius2fahrenheit]
testcase=int
size=1

[celcius2kelvin]
testcase=int
size=1

[changingbase]
testcase=int
size=3

[decimal2hex]
testcase=int
size=1

[fahrenheit2celcius]
testcase=int
size=1

[fahrenheit2kelvin]
testcase=int
size=1

[grosssalary]
testcase=int
size=1

[hex2decimal]
testcase=hex
size=1

[interestrate]
testcase=int
size=1

[kelvin2celcius]
testcase=int
size=1

[kelvin2fahrenheit]
testcase=int
size=1

[octal2decimal]
testcase=oct
size=1

[octal2hex]
testcase=oct
size=1

[cryptxor]
testcase=str
size=100

[addprime]
testcase=int
size=1

[areasquare]
testcase=int
size=1

[areatriangle]
testcase=int
size=1

[armstrongnumber]
testcase=int
size=1

[automorphic]
testcase=int
size=1

[averagesum]
testcase=int
size=10

[circumferencecircle]
testcase=int
size=1

[diagonaladdition]
testcase=int
size=1

[emi]
testcase=int
size=1

[fastmoduloexponentiation]
testcase=int
size=1

[gcd]
testcase=int
size=3

[lastdigitfibonacci]
testcase=int
size=1

[lcm]
testcase=int
size=1

[magicnumber]
testcase=int
size=1

[mirror]
testcase=int
size=1

[naivemodularinverse]
testcase=int
size=1

[palindromenumber]
testcase=int
size=1

[reversenumber]
testcase=int
size=1

[roots]
testcase=int
size=1

[russianpeasantmultiplication]
testcase=int
size=1

[squarearray]
testcase=int
size=1

[squareroot]
testcase=int
size=1

[volumecone]
testcase=int
size=1

[volumecylinder]
testcase=int
size=1

[volumesphere]
testcase=int
size=1

[linearsearch]
testcase=int
size=1

[bogosort]
testcase=int
size=1

[bucketsort]
testcase=int
size=1

[countingsort]
testcase=int
size=1

[heapsort]
testcase=int
size=1

[radixsort]
testcase=int
size=1

[anagram]
testcase=int
size=1

[reversestring]
testcase=str
size=1

#######################################
# Other dummys ########################
#######################################
#
##[dummy]
##testcase=fileinput
##size=1000
##type=string
##tescase in testcase fileinput_string_100.in
##args=<in> <out>
##outfilename=dummy.outfile
#
##[pic]
##testcase=fileinput
##size=40
##type=picture
##infile=

