[testcase_001]
    arguments = ["a",]
    stdout = "Result: 0x61\n"
    exit_code = 0

[testcase_002]
    arguments = ["hello",]
    stdout = "Result: 0x3ad49e92\n"
    exit_code = 0

[testcase_003]
    arguments = ["world",]
    stdout = "Result: 0xb0c71e6\n"
    exit_code = 0

[testcase_004]
    arguments = ["foo",]
    stdout = "Result: 0x45930a70\n"
    exit_code = 0

[testcase_005]
    arguments = ["bar",]
    stdout = "Result: 0x52cc5cb9\n"
    exit_code = 0

[testcase_006]
    arguments = ["12345",]
    stdout = "Result: 0x8f4f862d\n"
    exit_code = 0

[testcase_007]
    arguments = ["Hello, World!",]
    stdout = "Result: 0x167f416b\n"
    exit_code = 0

[testcase_008]
    arguments = ["coreutils",]
    stdout = "Result: 0x785be45e\n"
    exit_code = 0

[testcase_invalid_no_args]
    arguments = []
    stdout = ""
    exit_code = 2
