[testcase_valid]
    arguments = ["396.15",]
    stdout = "Result: 396.15°K = 123°C\n"
    exit_code = 0

[testcase_invalid]
    arguments = ["abc",]
    stdout = "Result: abc_2 is not a valid number.\n"
    exit_code = 1
