[testcase_001]
    arguments = ["a",]
    stdout = "Result: 0x620062\n"
    exit_code = 0

[testcase_002]
    arguments = ["hello",]
    stdout = "Result: 0x2820144\n"
    exit_code = 0

[testcase_003]
    arguments = ["world",]
    stdout = "Result: 0x2b0014e\n"
    exit_code = 0

[testcase_004]
    arguments = ["foo",]
    stdout = "Result: 0x13d00d6\n"
    exit_code = 0

[testcase_005]
    arguments = ["bar",]
    stdout = "Result: 0x13800d5\n"
    exit_code = 0

[testcase_006]
    arguments = ["12345",]
    stdout = "Result: 0x131009a\n"
    exit_code = 0

[testcase_007]
    arguments = ["Hello, World!",]
    stdout = "Result: 0x9780240\n"
    exit_code = 0

[testcase_008]
    arguments = ["coreutils",]
    stdout = "Result: 0x6600227\n"
    exit_code = 0

[testcase_invalid_no_args]
    arguments = []
    stdout = ""
    exit_code = 2
