/* Generated by Frama-C */
struct bar {
   int x ;
   struct bar *next ;
};
struct foo {
   int y ;
};
extern struct bar *global;

extern struct foo another;

void main(void)
{
  struct bar *b;
  b = global;
  b->x = 1;
  b->next = (struct bar *)0;
  another.y = 2;
  return;
}


