[testcase_true]
    arguments = ["153",]
    stdout = "Result: 153 is an Armstrong number.\n"
    exit_code = 0

[testcase_false]
    arguments = ["17",]
    stdout = "Result: 17 is not an Armstrong number.\n"
    exit_code = 1
