[testcase_001]
    arguments = ["a",]
    stdout = "Result: 0xaef5004d\n"
    exit_code = 0

[testcase_002]
    arguments = ["hello",]
    stdout = "Result: 0x6718efcb\n"
    exit_code = 0

[testcase_003]
    arguments = ["world",]
    stdout = "Result: 0x1462e1a9\n"
    exit_code = 0

[testcase_004]
    arguments = ["foo",]
    stdout = "Result: 0x1a9b05c8\n"
    exit_code = 0

[testcase_005]
    arguments = ["bar",]
    stdout = "Result: 0x1a9b0058\n"
    exit_code = 0

[testcase_006]
    arguments = ["12345",]
    stdout = "Result: 0x3e1ad64c\n"
    exit_code = 0

[testcase_007]
    arguments = ["Hello, World!",]
    stdout = "Result: 0x8becdfb1\n"
    exit_code = 0

[testcase_008]
    arguments = ["coreutils",]
    stdout = "Result: 0xe0364148\n"
    exit_code = 0

[testcase_invalid_no_args]
    arguments = []
    stdout = ""
    exit_code = 2
