[testcase_valid]
    arguments = ["123",]
    stdout = "Result: 123_8 = 83_10\n"
    exit_code = 0

[testcase_invalid]
    arguments = ["909",]
    stdout = "Result: 909_8 is not a valid number.\n"
    exit_code = 1
