[testcase_001]
    arguments = ["0",]
    stdout = "Result: 0x0\n"
    exit_code = 0

[testcase_002]
    arguments = ["1",]
    stdout = "Result: 0x1\n"
    exit_code = 0

[testcase_003]
    arguments = ["7",]
    stdout = "Result: 0x7\n"
    exit_code = 0

[testcase_004]
    arguments = ["10",]
    stdout = "Result: 0x8\n"
    exit_code = 0

[testcase_005]
    arguments = ["17",]
    stdout = "Result: 0xf\n"
    exit_code = 0

[testcase_006]
    arguments = ["77",]
    stdout = "Result: 0x3f\n"
    exit_code = 0

[testcase_007]
    arguments = ["100",]
    stdout = "Result: 0x40\n"
    exit_code = 0

[testcase_008]
    arguments = ["777",]
    stdout = "Result: 0x1ff\n"
    exit_code = 0

[testcase_missing_args]
    arguments = []
    stdout = ""
    exit_code = 2
